apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: vanix013/project:v6
        ports:
        - containerPort: 5000

